# Generated by Django 5.0.4 on 2026-04-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeranalytics',
            options={'ordering': ['-lifetime_value_score'], 'verbose_name': 'Customer Analytics', 'verbose_name_plural': 'Customer Analytics'},
        ),
        migrations.AlterModelOptions(
            name='orderanalytics',
            options={'ordering': ['-order_date', 'order_hour'], 'verbose_name': 'Order Analytics', 'verbose_name_plural': 'Order Analytics'},
        ),
        migrations.AlterField(
            model_name='customeranalytics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderanalytics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
