# Generated by Django 5.0.4 on 2026-04-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_alter_customeranalytics_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE customer_analytics DROP COLUMN IF EXISTS email_domain CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "ALTER TABLE order_analytics DROP COLUMN IF EXISTS currency CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "ALTER TABLE order_analytics DROP COLUMN IF EXISTS dominant_category CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "ALTER TABLE order_analytics DROP COLUMN IF EXISTS order_complexity_score CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='customeranalytics',
                    name='email_domain',
                ),
                migrations.RemoveField(
                    model_name='orderanalytics',
                    name='currency',
                ),
                migrations.RemoveField(
                    model_name='orderanalytics',
                    name='dominant_category',
                ),
                migrations.RemoveField(
                    model_name='orderanalytics',
                    name='order_complexity_score',
                ),
            ],
        ),
    ]
